/*
    2s complement in C
    ------------------------------------------------------------
    > The 2s complement in C is generated from the 1s complement in C.   
    > The 1s complement of a binary number is created by transforming bit 1 to 0 and 0 to 1. 
    > The 2s complement of a binary number is generated by adding one to the 1s complement of a binary number.

    Steps
    ------------------------------------------------------------
    1. Convert Decimal Number to Binary Number 
    2. Represent the Binary Number to at least 8-bit Number 
    3. From Right-to-Left, after matching first bits with 1, then invert each bit. 
    4. The left-most-bit is the sign-bit. 
    5. Convert all bits (without sign bit), to binary-to-decimal converstion. 

    Example:
    ------------------------------------------------------------
    35  : 100011
    35  : 0010 0011 (8-bit representation)
    ~35 : 1101 1100 
        : -(1 x 2^6) + (0 x 2^5) + (1 x 2^4) + (1 x 2^3) + (1 x 2^2) + (0 x 2^1) + (0 x 2^0)
        : -64 + 28
        : -36
*/


#include <stdio.h> 
#include <stdint.h> //For using "Fixed width integer types" i.e uint8_t 

void myExample1(void); //Function prototype declaration 
void myExample2(void); //Function prototype declaration 


int main(void)
{
    //myExample1();
    myExample2();



    return 0;
}




void myExample1(void) //Function Body
{
    int i = 35; 
    int ans = ~(i);

    printf("Answer is: %d\n", ans);
    
}


void myExample2(void) //Function Body
{
    uint8_t bitNumber = 0; 

    printf("Type the number of bit you want to enter: ");
    scanf("%d", &bitNumber);

    char binary[bitNumber]; 
    char onesComplement[bitNumber]; 
    char twosComplement[bitNumber]; 

    printf("\nEnter the binary number: ");
    scanf("%s", binary);

    {
        printf("\nOnes Complement of the binary number is: ");

        //Finding onesComplement in C
        for(uint8_t count = 0; count <= bitNumber; count++)
        {
            if(binary[count] == '0') binary[count] = '1'; 
            else if(binary[count] == '1') binary[count] = '0'; 
        }

        printf("%s", binary);
    }
    
}
